
name: Atlas Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Atlas
        run: |
          curl -X POST https://run.atlas.in.net/deploy             -H "Content-Type: application/json"             -d '{
              "token": "deploy_93565293e9bf1674891f85d8d66b5498",
              "domain": "undefined",
              "image": "ghcr.io/${{ github.repository }}:latest",
              "name": "${{ github.event.repository.name }}"
            }'
